### PR TITLE
Support polymorphic objects

### PR DESCRIPTION
**Pull request by ubaumann**
Fix polymorphic object issue: https://github.com/dmkoch/django-jsonfield/issues/101

With polymorphic objects I get a `AttributeError` on `obj.pk`. `obj.id` works fine. `pk` and `id` has in the tests always the same value.

### CODE REVIEW

**Comment by nemesisdesign** [comment]
@ubaumann could you add a test for your fix and ensure it fails if you revert your patch?

**Comment by youssefm** [comment]
I can confirm this appears to fix https://github.com/dmkoch/django-jsonfield/issues/101. Without this change, JSON fields on parents don't get deserialized properly and are returned as strings instead.

**Comment by ubaumann** [comment]
@youssefm Thank you. I hadn't considered that.

@nemesisdesign I can add some test but it would add the dependency `django-polymorphic`.

**Comment by ubaumann** [comment]
@nemesisdesign Should I add some tests? The fix is working well in our production environment.

**Comment by nemesisdesign** [comment]
I'm not a maintainer of this package, but unless django-polymorphic is too heavy, I would add it only as a dependency for the build. This kind of dependency is usually added in a file called `requirements-test.txt`

**Comment by ngaranko** [comment]
Hi All, my project depends on this PR, is there anything I can help with to get it merged?

**Comment by youssefm** [comment]
Just my two cents here - the current fix may address the specific issue with `django-polymorphic`, but I don't believe it fixes the more general problem that JSONField has, namely that a JSONField on a parent class gets deserialized as a string when an instance of the child class gets deserialized.

It seems to me that it would make more sense to fix the broader issue here rather than trying to detect instances of a particular library in order to treat them differently.

**Comment by rpkilby** [comment]
Hi all. I've added tests that ensure that jsonfield is compatible with MTI inheritance. If you have any further issues, please let me know. Thanks!

**Pull request closed without merging**
